# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: object-Object
book_id: hexcasting:thehexbook
default_branch: '1.19'
github_repo: hexbound
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexboundModPlugin
hexdoc_plugin_classname: HexboundPlugin
java_lang:
    ext: kt
    src: kotlin
java_package: coffee/cypher/hexbound
mod_display_name: Hexbound
modid: hexbound
multiloader: false
package_export_root: doc/src/hexdoc_hexbound/_export
package_name: hexdoc-hexbound
package_slug: hexdoc_hexbound
package_src: doc/src/hexdoc_hexbound
pages_url: https://hexbound.hexxy.media/
pattern_regex:
    per_world_value: 'true'
    regex: HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*modLoc\("(?P<name>[^"]+)"\)[^;]+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:[^;]*(?P<is_per_world>true)\);)?
pattern_registry: init/HexboundPatterns.kt
