modid = "hexbound"
book = "hexbound:hexboundbook"
extra_books = [
    "hexal:hexalbook",
]
default_lang = "en_us"
default_branch = "1.19"

resource_dirs = [  # top takes priority
    "resources",
    "{$_paths.resources}",
    { modid="hexal" },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexbound/_export/generated"

[textures]
missing = [
    "minecraft:shield",
    "minecraft:chest",
    "hexal:*",
]

[template]
icon = "{$_paths.resources}/assets/hexbound/icon.png"
include = [
    "hexbound",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexbound"
author = "Cypher121"
show_landing_text = false

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex."!Raw" = 'HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"(?:.|\n)+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:(?:(?!registerPattern)(?:.|\n))*?\n\s*(?P<is_per_world>true),?\n\s*\))?'
_per_world_value = "true"

[[extra.hexcasting.pattern_stubs]]
path = "{$_paths.kotlin_package}/init/HexboundPatterns.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

[_paths]
src = "../src"
resources = "{src}/main/resources"
kotlin_package = "{src}/main/kotlin/gay/object/hexbound"
