name: Build the web book

# TODO: move publishing into release.yml
on:
  push:
    branches: "1.19"
  workflow_dispatch:
    inputs:
      release:
        description: Release this version
        type: boolean
        default: false
      publish:
        description: Package index to publish to
        type: choice
        options:
          - none
          - PyPI

env:
  PYPI_PACKAGE: hexdoc-hexbound

permissions:
  contents: read

jobs:
  hexdoc:
    uses: hexdoc-dev/hexdoc/.github/workflows/hexdoc.yml@v1!0.1.dev
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: '3.11'
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release }}

  publish-pypi:
    runs-on: ubuntu-latest
    needs: hexdoc
    if: needs.hexdoc.outputs.release == 'true' && inputs.publish == 'PyPI'
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
